### ISSUE TITLE
No getenv?

### ISSUE THREAD

**Issue by runeimp** [ldarren/QuickJS#1]
I'm pretty excited about QuickJS and look forward to getting more familiar with it!  😃

But In a test I got the following while compiling some test JS

```bash
$ qjsc -o hello_env_bin hello_env.js
$ HELLO=Environment ./hello_env_bin
ReferenceError: getenv is not defined
    at <eval> (hello_env.js:1)
```

The source is simply 

```javascript
arg = getenv("HELLO")

x = "Hello, " + arg + "!"

console.log(x)
```

Got the same error using shebang version

```bash
$ HELLO=Environment ./hello_env
ReferenceError: getenv is not defined
    at <eval> (./hello_env:3)
```

The source is the same as above with the addition of the shebang `#!/usr/bin/env qjs` and making the file executable. That is with the Homebrew install version of QuickJS. I also tried compiling and executing the script version using locally compiled QuickJS binaries based on an unmodified clone of the github repo. Same error using either binaries for compiling interpreting. Other tests getting command line arguments and other simpler tests worked fine.  😀 

This is on a 2019 MacBook Pro w/32 GB of RAM running macOS Mojave v10.14.5. I can also test on a 2012 iMac w/24 GB of RAM running the same OS when I get home if desired.

**Comment by ldarren** [comment]
hi @runeimp thanks for the investigation, i see a lot of potential in QuickJS as well

I don't think getenv is a js function, where did you use getenv before?

**Comment by runeimp** [comment]
I used `getenv(name)` when I started playing with JavaScript command line tools with [JSDB](http://www.jsdb.org/) before [Node](https://nodejs.org/) came into being. But there are similar functions in Node, and a few others for getting environment variables I've used in the past. I have a repo [Hello Notes](https://github.com/runeimp/hello) where I figure out in many languages how to do a "Hello, World!" using strings, variables, args and env vars in each language. And have tried several JavaScript engines. And wow, I really need to update my repo. Never posted any of my JavaScript stuff to it. 👼

I found a reference to `getenv(name)` in the docs [std-module](https://bellard.org/quickjs/quickjs.html#std-module) section. I also found references in `quickjs-libc.c` that suggested it might be the same. Especially on [line #890](https://github.com/ldarren/QuickJS/blob/5c9d67e87abd127266a92e7787df922f44b895e9/quickjs-libc.c#L890). I only know a little C but haven't done anything like embedding a scripting language in a host language. But that line looked to me like you were making a function definition for JavaScript that accessed a C function. So I tried it and got the error above.

**Comment by duzun** [comment]
Isn’t it ‘std.getenv(“varName”)’?

**Comment by ldarren** [comment]
@duzun is right, it is mentioned in [quickjs doc](https://github.com/ldarren/QuickJS/blob/mod/doc/quickjs.html#L463-L558) you can do a quick test it with ./qjs

```javascript
std.getenv('PATH')
```

**Comment by runeimp** [comment]
Ah, I should have thought of that. Of course it's part of the module and the std module needs to be accessed directly. I was just confused by the fact that **3.3 Standard library** has **3.3.1 Global objects** which is just above **3.3.2 std module** so I expected the std module's methods to be globally accessible. There are 9 example of things that use the `std.` prefix and I just didn't review those parts. Though it would be nice is if it was explicitly stated at the top of the std module section or used more consistently in the method's individual descriptions. But that is largely a minor point in general.

**Comment by runeimp** [comment]
Dang, closed too soon. So `std.getenv("name")` works in a shebang script. But I still get an error when trying to compile 

```bash
$ qjsc -o hello_env_bin hello_env.js
$ HELLO=Environment ./hello_env_bin
ReferenceError: std is not defined
    at <eval> (hello_env.js:1)
```

So I tried importing it with `import * as std from "std";` as found in `repl.js` and elsewhere and tried compiling again and got

```bash
$ qjsc -o hello_env_bin hello_env.js
SyntaxError: unsupported keyword: import
    at hello_env.js:2
```
I also tried

```bash
$ qjsc -M std -o hello_env_bin hello_env.js
SyntaxError: unsupported keyword: import
    at hello_env.js:1
```

I'm sure I'm likely doing something wrong but I'm not finding anything in the docs on how to do it write. That or the compiler doesn't support the std module yet or is this is possibly a macOS specific bug?

**Comment by isanimu** [comment]
@runeimp You just need to add -m, it will compile as Javascript module.

```
import * as std from "std";

const arg = std.getenv(`HELLO`);
const x = `Hello, ${arg}!`;

console.log(x);
```

```
$ qjsc -m -o hello_env hello_env.js
$ HELLO=Environment ./hello_env
```

**Comment by runeimp** [comment]
Thanks @isanimu. I'd read the `-m` switch as only for creating JS modules for external use. Not to also compile an (existing?) C to JS module into your current code. Appreciate the clarification. 😀
