### ISSUE TITLE
QuickJS website

### ISSUE THREAD

**Issue by ChristoPy** [ldarren/QuickJS#14]
I've been using QuickJS for a few days and started wondering if you have some plans to create a website.
I don't know if it's an ideia of yours but it can be so much helpful to people learn more about the engine and also have a better place to find a documentation about.

I say it because I found myself a couple times comming back to the PDF file, trying to understand wich function should be used for each purpose. And I think that this could be happening to other people too.

If there's a plan for this, or not, I would like to help with the website and a documentation area with code examples for the engine.

**Comment by ldarren** [comment]
@ChristoPy this repo is for my own usages, the official development discussion channel can be found at https://www.freelists.org/archive/quickjs-devel/05-2020

**Comment by medemi68** [comment]
I agree with this. It might be helpful to have code examples as well so that beginners can better understand what's going on and how to implement QuickJS in their projects.

**Comment by Cyberfonic** [comment]
I am porting an in-house system from [Duktape](https://duktape.org) to [quickJS](https://bellard.org/quickjs/) to take advantage of the support for ES6 features and good module support (including dynamic imports).

Have ported some simple class libraries to be imported as shared object modules. But getting stumped with more advanced inter-operation issues. quickjs.h contains approximately 400 entries, but there are less than 2 pages of documentation for the C-API.

Any suggestions as to where more detailed documentation could be found? Failing that pointers to any well documented project using quickJS might help. Yes, I have Googled and haven't found anything useful.

**Comment by ldarren** [comment]
I don't have the resource and time to maintain a documentation for quickjs. but do let me know what else can i help

**Comment by medemi68** [comment]
@ChristoPy I'd be willing to help contribute if you decide to create a website with some documentation. QuickJS is far superior to Duktape and Jerryscript but it lacks the one thing that would give it reach.

@ldarren perhaps you could help us help you? Even a simple document explaining how you can use QuickJS in your own projects would be helpful to new users.

**Comment by ChristoPy** [comment]
@medemi68 Sorry for the late response!
If you still willing to help, I can do it without any problems :smile:
