### ISSUE TITLE
Array.prototype.fill optimisation

### ISSUE THREAD

**Issue by nagayev** [ldarren/QuickJS#16]
My code:
`
var a = new Array(10**9);
a=a.fill(0);
`
So I suggest:
1. Add memory limit e.g 2GB RAM
2. Add optimization for such arrays (like PHP Immutable arrays)
<code>
  $a=array();  
  for($i=0;$i<1000000;$i++) $a[$i]=array("hello")  
memory_get_usage(true) //about 34mb
</code>

**Comment by ldarren** [comment]
Array size according to ECMA-262 5th Edition specification is 2^32 - 1

for immutable array, have you tried `Object.freeze(a)`?

**Comment by nagayev** [comment]
@ldarren Not just immutable, but less size in memory.
Okey, I didn't know about max Array size.

**Comment by nagayev** [comment]
@ldarren So in order to save memory we can store array as I suggested in my previous comment and after array's edit we can use standart variant

**Comment by ldarren** [comment]
@nagayev this optimisation may not be as useful as you thought. unless many ppl using single value filled large array. what is the use case of pre-filled a large array in js?

**Comment by nagayev** [comment]
@ldarren Dmity Stogov, one of core PHP developers, said that this optimisation maybe used for small arrays

**Comment by ldarren** [comment]
@nagayev official quickjs github repo has been setup, please open a issue there https://github.com/bellard/quickjs/issues

**Comment by ldarren** [comment]
moved to official issues
