### ISSUE TITLE
InternalError exception in String.prototype.padStart

### ISSUE THREAD

**Issue by h2oche** [ldarren/QuickJS#18]
OS : macOS ver 10.15.3
Version: QuickJS version 2020-07-05

When following JavaScript code is executed, QuickJS throws `InternalError` exception.
```js
"use strict";
var x = "42".padStart(Infinity, "");
console.log(x);
```

However, according to ECMA-262 specification(https://tc39.es/ecma262/), output of script above should be "42". 

In "[21.1.3.15.1 Runtime Semantics: StringPad](https://tc39.es/ecma262/#sec-stringpad)",
- in step 3, `intMaxLength` is 2^53 -1 because `ToLength(Infinity)` is  2^53 -1
- in step 4, `stringLegnth` is 2
- in step 5, condition expression is false, so doesn't return
- in step 7, `fillString` is `""` and therefore `filler` is also `""`
- in step 8, `filler` is same with empty String, so return value of this algorithm is "42"

This works correctly on Node.js.

**Comment by ldarren** [comment]
@h2oche  the official quickjs github repo has been setup, please open a issue there https://github.com/bellard/quickjs/issues

**Comment by h2oche** [comment]
@ldarren Thank you for your notice.
