### ISSUE TITLE
Incompatible with 64-bit?

### ISSUE THREAD

**Issue by mehrdadn** [ldarren/QuickJS#3]
Hi, I was wondering if you know whether this project is 64-bit compatible?  
I ask because I noticed the following line in `JS_NewObjectFromShape` seems problematic:

    return JS_MKPTR(JS_TAG_OBJECT, p);

The definitions of `JS_TAG_OBJECT` and `JS_MKPTR` are:

     JS_TAG_OBJECT      = -1,
    #define JS_MKPTR(tag, ptr) (((uint64_t)(tag) << 32) | (uintptr_t)(ptr))

This seems to completely clobber the upper half of a 64-bit pointer... does this mean the project is 32-bit only?

**Comment by ldarren** [comment]
there are 3 version of JS_MKPTR, the one you referring to is only enabled for JS_NAN_BOXING which for non 64 bit arch

see quickjs.h [line 64](https://github.com/ldarren/QuickJS/blob/master/quickjs.h#L64) and [line 124](https://github.com/ldarren/QuickJS/blob/master/quickjs.h#L124)

there is a good explanation of nan boxing [here](https://anniecherkaev.com/the-secret-life-of-nan)
