### ISSUE TITLE
[Question] Heap snapshot

### ISSUE THREAD

**Issue by kefniark** [ldarren/QuickJS#4]
## Description
Quite exited by this project, this is really cool and I like the lightweight part of it 👍 (I was used to embed v8 or chakra core before).

I was wondering if Heap snapshot is on the roadmap ?

For the moment:
* Only v8 seems to have this feature, but it's a bit slow
* Hermes has it on the roadmap for month, but it does not look like a priority to them and android apps

**Comment by ldarren** [comment]
I'm looking forward to that feature too, but it is not shown in the todo list yet, the nearest thing i could find is https://github.com/ldarren/QuickJS/blob/master/TODO#L67
