### ISSUE TITLE
qjsc fail: gcc: error: /usr/local/lib/quickjs/libquickjs.a: No such file or directory

### ISSUE THREAD

**Issue by zaverden** [ldarren/QuickJS#5]
Thank you for a great job. I tried QuickJS and came across an error in `qjsc`

My steps:
1. Install prerequisites and build by `make` command - success with no errors
1. Write a simple script and run it by `./qjs -m script.js` - success
1. Compile by `./qjsc -m script.js` - success
1. Copy `script.js`, `qjs` and `qjsc` to a new empty folder
1. Run `./qjs -m script.js`  - still works
1. Run `./qjsc -m script.js` - error
```
gcc: error: /usr/local/lib/quickjs/libquickjs.a: No such file or directory
```
I also tried to add repo folder to `$PATH` and run compilation as `qjsc -m script.js` - same `gcc` error while `qjs -m script.js` works great.

OS: `Ubuntu 18.04.3 LTS`
QuickJS commit: https://github.com/ldarren/QuickJS/tree/c74fd789

**Comment by zaverden** [comment]
I also have found a `libquickjs.a` file in repo folder and copied it to location from an error message. Error message changes to

```
/tmp/out9232.c:3:10: fatal error: quickjs-libc.h: No such file or directory
 #include "quickjs-libc.h"
          ^~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by ldarren** [comment]
hi @zaverden qjsc needs static lib .a to create binary.

to create binary outside of repo, you should install qjsc by `sudo make install`

after that you should be able to run qjsc outside of repo

**Comment by zaverden** [comment]
Thank you, @ldarren, `sudo make install` did a magic.
