### ISSUE TITLE
Known issues...

### ISSUE THREAD

**Issue by i404788** [ldarren/QuickJS#6]
In the readme you have `known issues` however these aren't issues. 

QuickJS implements [ES2019](https://www.ecma-international.org/ecma-262/9.0/index.html), and a Subset of ES2020. 
It doesn't implement the [HTML standard](https://html.spec.whatwg.org/multipage/workers.html), which defines WebWorkers, nor the [W3C standard (File API)](https://w3c.github.io/FileAPI/) which defines blobs Blobs.

To find the actual known issues check: https://github.com/ldarren/QuickJS/blob/mod/TODO and https://bellard.org/quickjs/quickjs.html#Language-support

**Comment by ldarren** [comment]
that section was written at POV of a javascript programmer, just like when comparing ie8 js to modern day js. may not be an issue to the creator but is an issue to js developer
